services:
  bodylog:
    image: szuryuu/bodylog:v1.0.0
    container_name: bodylog
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - bodylog_data:/data
    environment:
      DB_PATH: /data

volumes:
  bodylog_data:
